### ISSUE TITLE
Fix error messages

### ISSUE THREAD

**Issue by rgrinberg** [ocamllabs/vscode-ocaml-platform#112]
Currently, the plugin shows error messages like this:

```
Toolchain initialisation failed: Exec failed during /usr/local/bin/esy command-env --json -P /Users/rgrinberg/github/esy/esy
```

It's better to just log such a message and only present relevant information to the user.

**Comment by mnxn** [comment]
Getting a "Toolchain initialisation failed" is now unlikely when using a non-custom toolchain. As of #322, command errors will show the stderr that they failed with and instruct the user to look in the output channel for more information:
https://github.com/ocamllabs/vscode-ocaml-platform/blob/c434837b61a678db0d3d3a70c7951d2fcc9caf15/src/Cmd.ml#L93

I'm going to close this. Feel free to reopen if you think otherwise.
