### ISSUE TITLE
Markdown codeblock syntax highlight being influenced

### ISSUE THREAD

**Issue by liwd190019** [ocamllabs/vscode-ocaml-platform#1288]
The syntax highlight in codeblock of markdown file is influenced by this extension when code contains: `ml`, `ocaml`, `re`, `reason`, `reasonml` with at least one whitespace character. Example:

<img width="988" alt="Screenshot 2023-11-24 at 3 53 19 AM" src="https://github.com/ocamllabs/vscode-ocaml-platform/assets/97966234/4b018e2c-f156-4557-8197-f783e23d9a03">

See the red curly brackets in the figure.
After looking through the source code, I think probably the issue lies on these two files: `syntaxes/ocaml-markdown-codeblock.json` and `syntaxes/reason-markdown-codeblock.json` where  the regex of `"begin": ...` may see any of these key words(ml, ocaml, re, ...) as the beginning of an ocaml codeblock.

This shouldn't be a big issue. I tried to fix this by using a new regex, the one that is employed in [vscode source code](https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json) but failed. Maybe other factors account for this issue.  I really hope you can teach me how to fix this. Or maybe I can make a pr if you are willing to give me some hints? :)

Luckily, the markdown preview is not influenced.

**Comment by ssfrr** [comment]
I just ran into this also. It took me a bit to figure out that it was related to the ocaml extension because it was showing up in cases that had nothing to do with ocaml code. In my case it was any time the word "feature" appeared in a comment. For instance, a markdown file with the following contents:

```
    this is a test

    ```python
    x = 4
    # feature
    # testing
    ```
```

I get highlighting that looks like this:

![image](https://github.com/ocamllabs/vscode-ocaml-platform/assets/734386/3ca8decf-5365-4dcf-93e5-462e6e42f83b)

Notice that the 2nd line of comment isn't highlighted as a comment.

If I change the word "feature" (adding or removing a character), both lines show up as comments.
