### ISSUE TITLE
Linting mli Files

### ISSUE THREAD

**Issue by zevbo** [ocamllabs/vscode-ocaml-platform#425]
One issue I run into a lot while using the plugin is that the linter doesn't catch mli vs. ml type mismatches.
Just for an example:
consts.ml:
```ocaml 
let g = 9.81
```
consts.mli:
```ocaml 
val g : string
```

The linter shows no error in consts.mli, but when I run dune build, it throws:

File "virtuality2d/src/consts.ml", line 1:
Error: The implementation virtuality2d/src/consts.pp.ml
       does not match the interface virtuality2d/src/.virtuality2d.objs/byte/virtuality2d__Consts.cmi:
       Values do not match: val g : float is not included in val g : string
       File "virtuality2d/src/consts.mli", line 1, characters 0-14:
         Expected declaration
       File "virtuality2d/src/consts.ml", line 1, characters 4-5:
         Actual declaration

Is there any way that Merlin VS code plugin could catch this in the linter?

**Comment by mnxn** [comment]
I'm not sure if Merlin could catch this type of error.

Since it shows up when building with dune, it should be possible for it to show up when using the dune task provider. The problem matcher should be picking up mult-line errors (#229), but I can't get it to work right now.

**Comment by rgrinberg** [comment]
Let's see if @Khady is aware of this issue with the problem matcher.

This issue is indeed something that should be picked up when you build the project. It's plausible to make merlin handle this kind of error checking as well, but you'd need to convince them first.

I'm closing this issue as there's nothing we can do our on our side, but cc'ing a merlin dev @voodoos for awareness.

**Comment by Khady** [comment]
https://github.com/ocamllabs/vscode-ocaml-platform/blob/1adcf20b3549ecd576522c34d06970a9fb389c01/package.json#L200

The problem matcher is partially incorrect. It won't match `File "virtuality2d/src/consts.ml", line 1:` because there is no `, characters 23-26` part. I think it should be changed to `^\\s*\\bFile\\b\\s*\"(.*)\",\\s*\\blines?\\b\\s*(\\d+)(?:-(\\d+))?(?:,\\s*\\bcharacters\\b\\s*(\\d+)-(\\d+)\\s*):\\s*$` but I don't have time to do a proper test right now.

**Comment by voodoos** [comment]
Is there some plan to support a feature similar to `dune build --watch` in the plugin ? 
This could allow the first build error to always be reported.

**Comment by rgrinberg** [comment]
> Is there some plan to support a feature similar to dune build --watch in the plugin ?

Indeed there are such plans.

**Comment by Khady** [comment]
> Is there some plan to support a feature similar to dune build --watch in the plugin ?

until the extension is able to talk to dune directly, you can have a background task in vscode. Something like this should work

```
    {
      "label": "byte watch",
      "type": "shell",
      "command": "opam exec -- dune build src/main.bc -w",
      "isBackground": true,
      "group": "build",
      "options": {
        "cwd": "${workspaceFolder}/path/to/project",
        "env": {
          "OCAML_ERROR_STYLE": "short"
        }
      },
      "problemMatcher": {
        "base": "$ocamlc",
        "source": "dune2",
        "fileLocation": [
          "relative",
          "${workspaceFolder}/path/to/dune/project/root"
        ],
        "background": {
          "activeOnStart": true,
          "beginsPattern": "^.*NEW BUILD.*$",
          "endsPattern": "^.*waiting for filesystem changes.*$"
        }
      }
    },
```

**Comment by rgrinberg** [comment]
> until the extension is able to talk to dune directly, you can have a background task in vscode. Something like this should work

Note that we'll need to fix the problem matcher regardless. Dune isn't going to be able to extract locations out of the compiler more accurately (although perhaps it should).
