### ISSUE TITLE
Extension is unable to find ocamllsp automatically.

### ISSUE THREAD

**Issue by AntouanK** [ocamllabs/vscode-ocaml-platform#430]
Hi there.

I'm trying to understand how to use the plugin.
I keep getting the 
```
Extension is unable to find ocamllsp automatically. Please select package manager you used to install ocamllsp for this project.
```
message.
I select global and then I get the
```
Toolchain initialisation failed: Command "ocamllsp" not found
```

I do have it installed
```
❯ which ocamllsp 
/home/antouank/.opam/default/bin/ocamllsp
❯ opam install ocaml-lsp-server
[NOTE] Package ocaml-lsp-server is already installed (current version is 1.1.0).
```

And I tried to set `zsh` as the shell to the plugin, no difference.
What can I do to set it up?

( using manjaro linux )

Thank you.

**Comment by ulugbekna** [comment]
1. Are you setting the sandbox to `default` opam sandbox? (that's where your `ocamllsp` is installed according to `which`) Because if not, the sandbox that you indicated may not have ocamllsp installed.
2. Maybe also try running `eval $(opam env)` in command line? (and restarting the window) 
3. As a last resort: run vscode from command line when you're in the root directory of your project.

**Comment by AntouanK** [comment]
oh, I see.
first option was "Global" so I was choosing that.
Yeah, changed to default and it works fine!

Thank you.

**Comment by idkjs** [comment]
>     3\. As a last resort: run vscode from command line when you're in the root directory of your project.

 🚀
