### ISSUE TITLE
Syntax highlighting for *.{ml,mli} misses contrast

### ISSUE THREAD

**Issue by smelc** [ocamllabs/vscode-ocaml-platform#562]
First of all, thank you for work on this extension, which I use many hours per working day and I'm very happy of it :pray:

However, I'd like to mention things in the default syntax highlighter which I think can be improved. I'm used to the syntax highlighting of [vscode-reasonml](https://github.com/reasonml-editor/vscode-reasonml) which has more contrast, and I think some of it could be reproduced. Please read this issue as a list of suggestions.

**TL;DR** too much blue

To make my point, let's compare the same file highlighted with `vscode-ocaml-platform`:

![](https://i.imgur.com/uKqJsAg.png)

and with `vscode-reasonml`:

![](https://i.imgur.com/0OSwVeE.png)

I think the second is less eyes-straining, because of a few simple differences:

* Keywords have different colors, for example `module`. It shouldn't be of the same color as the `let` introducing functions, since they are at different levels. The same goes for `let` introducing top-level functions, and nested `let`. The former introduce visible symbols while the latter are implementation details. It makes sense to have them of different colors.
* Operators (`>>=`, `|>`, `>>?=`) have a different color than regular functions. That's good because formatters usually put symbols at the start of lines, hereby presenting operator-heavy code like lists.
* Variant constructors have a different color and font than keywords. Once again, seems legit, because they are different things.
* Parentheses and `struct .. end` are not white. I think this is good, this differentiates them from functions and values, despite being close.
* Finally, the colon introducing types has a color different from names of variables and from types; making it clear it's a separator. The same goes for `=` introducing function bodies and `->` in patterns. They have a color different from their neighbors, making them easy to parse.

Note that there are things I like better in `vscode-ocaml-platform`:

* docstrings show identifiers :+1: 
* Format strings highlight specifiers :+1: 

## Workaround

One can use `vscode-reasonml` highlighting in this extension by copying its files (the `freebroccolo*` ones) in here:

```diff
diff --git a/package.json b/package.json
index 734850c..2fd8907 100644
--- a/package.json
+++ b/package.json
@@ -718,12 +718,12 @@
       {
         "language": "ocaml",
         "scopeName": "source.ocaml",
-        "path": "./syntaxes/ocaml.json"
+        "path": "./syntaxes/freebroccolo.json"
       },
       {
         "language": "ocaml.interface",
         "scopeName": "source.ocaml.interface",
-        "path": "./syntaxes/ocaml.interface.json"
+        "path": "./syntaxes/freebroccolo-interface.json"
       },
```

I used to do that, but it's inconvenient. You need to do that everytime `vscode` automatically updates `vscode-ocaml-platform`.

## Adoption

We're dealing with a subjective matter here: small steps can be taken, by doing small changes and see if people are happy.

Once again, thank you for hard work, very much appreciated :heart:

**Comment by mnxn** [comment]
Thank you for the suggestions, but I don't think there's much we can currently do to improve the colors of the default dark theme without degrading the syntax highlighting for most other themes.

The way that syntax highlighting works in VSCode has no concept of colors. For example, if you take a look at [ocaml.json](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/syntaxes/ocaml.json), you will see that the grammar is defined in terms of token names. I tried to use standard token names that would be recognized by most themes.

The problem is that the default VSCode dark theme isn't very good at using different colors for certain types of token. If you try using Monokai, another preinstalled theme, it looks much better:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/25037249/110955785-cbf3f900-82fe-11eb-9c85-df06b74cfbc8.png">


As for the previous syntax highlighting, it had plently of problems itself: it was inconsistent and buggy, sometimes failing to highlight certain constructs. The new grammar is much less fragile and uses established conventions for token names. 

I think most of the problems you list are solved by using a different color theme. In addition to Monokai, there are a few more that are preinstalled. And if those are lacking, there are plenty of [custom themes available on the extension marketplace](https://marketplace.visualstudio.com/search?target=VSCode&category=Themes&sortBy=Installs). Some themes will even use italics or bolding if you like that type of thing.

For highlighting parentheses, I like using the [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) extension because it distinguishes nested parentheses with different colors.

Semantic highlighting (https://github.com/ocamllabs/vscode-ocaml-platform/issues/432, https://github.com/ocaml/ocaml-lsp/issues/326) could add distinct highlighting for tokens that are hard to distinguish in the grammar alone (modules vs. variants, values vs. types) but there's a lot of work needed to support it.

**Comment by smelc** [comment]
Thanks for the detailed explanation and the pointers, very much appreciated :+1: I didn't know that a theme could map things identified differently by the parser to a common color and font. Knowing that, it makes sense that changing the theme will change a lot. For future readers, here's what my example looks like with a theme distinguishing more tokens (dark-dracula):

![](https://i.imgur.com/Atjudwe.png)

This is much better :+1:
