### ISSUE TITLE
Syntax highlight doesn't work for files called `meta.ml` or `META.ml`

### ISSUE THREAD

**Issue by Kakadu** [ocamllabs/vscode-ocaml-platform#564]
`meta2.ml` is working fine. Can you double-check?

**Comment by mnxn** [comment]
The OCaml highlighting doesn't work because it think it's a findlab META file:
https://github.com/ocamllabs/vscode-ocaml-platform/blob/41ff847a6c8fcec940154777299bf81b84fabd20/package.json#L581

http://projects.camlcity.org/projects/dl/findlib-1.8.1/doc/ref-html/r759.html

Removing it would prevent suffixed META files from being highlighted automatically, but I suppose it's better than interfering with syntax highlighting of other files.
