### ISSUE TITLE
Allow multiple sandboxes

### ISSUE THREAD

**Issue by wokalski** [ocamllabs/vscode-ocaml-platform#581]
In a monorepo setup we sometimes want to use multiple sandboxes. Depending on the directory you're in, you might want to use the closest esy.json/.opam from there.

**Comment by naartjie** [comment]
I just tried to write a wrapper using `./myscript.sh $prog $args`, but I noticed that `ocamllsp` gets started once, and all files get set to it.

At the moment it looks like there is no way to hand off to a different `ocamllsp` version based on the current file.

**Comment by mnxn** [comment]
If I'm understanding correctly, you're opening the entire monorepo as a folder in VSCode and want different sub folders to be able to use different sandboxes?

Is there a reason you can't open each subfolder in individual VSCode windows instead? VSCode will use the local `.vscode/settings.json` to determine the sandbox for each folder.

**Comment by wokalski** [comment]
Your understanding is correct. It's slightly inconvenient to do what you described.

**Comment by mnxn** [comment]
With the proposed language server protocol, it seems possible to have different language servers for different *workspace folders*:

https://github.com/Microsoft/vscode-extension-samples/tree/main/lsp-multi-server-sample

It doesn't seem possible to have different language server for arbitrary sub folders though.

**Comment by naartjie** [comment]
Thanks @mnxn I think per-workspace would work 💯 

I'm not sure how difficult it would be to make that work with VSCode OCaml Platform. If someone could point me in the right direction, I could try have a go at creating a PR?

**Comment by davesnx** [comment]
Hey, adding my issue here.

Would be useful when sharing code between frontend and backend. Using BuckleScript (OCaml 4.06) and OCaml 4.11 shows the error about merlin handling different versions.

```
/node_modules/bs-css-emotion/lib/ocaml/Css.cmi
seems to be compiled with OCaml 4.06.
But this instance of Merlin handles OCaml 4.11.
ocamllsp
```

I'm adding it here since would be great to point each folder to a specific `"ocaml.sandbox"` since you could point to different ocaml-lsp which reads different OCaml versions. This might make the error go away and makes the need to open 2 different windows go away, but It would introduce the issue of jump-to-definition or any feature that tries to go from one workspace to other.

Probably there are better ways to solve this exact issue, like BuckleScript updating to latest.

**Comment by naartjie** [comment]
> It would introduce the issue of jump-to-definition or any feature that tries to go from one workspace to other.

Wouldn't jump to definition still work, because regardless of the ocaml/ocaml-lsp version being used, the sources would still be available? (I might be missing something though)

**Comment by tmattio** [comment]
I'm not sure we will want to support this. VSCode's support for multiple workspaces is there to address this use case already. And the liveshare limitation sounds like something that should be addressed in liveshare rather than here.

I'll close the issue for now, but we'll consider re-opening it if there's enough user feedback in favor of adding support for multiple sandboxes.
