### ISSUE TITLE
Unable to locate module.

### ISSUE THREAD

**Issue by junknet** [ocamllabs/vscode-ocaml-platform#676]
<img width="482" alt="qwe" src="https://user-images.githubusercontent.com/55597646/127997839-3567dcb1-870f-496a-910e-758765e9ae57.png">

vscode log:
[Error - 下午5:54:55] Locate failed. not in environment: the
[Error - 下午6:02:06] Locate failed. not in environment: Mpz

The OCaml toplevel, version 4.12.0
OS: ArchLinux_x86

**Comment by etanter** [comment]
same problem here, on macOS. Used to work fine (when I last taught my compiler course, last year...). Updated to ocaml 4.12, new version of ocaml-lsp, new version of the platform, etc.

`open Printf` works fine.
`open Fmt` shows red, despite the fact that the package was installed (via opam)
`open Lib` where `lib` is a local module declared in Dune also shows red.

<img width="714" alt="Screen Shot 2021-08-17 at 11 52 52 AM" src="https://user-images.githubusercontent.com/1315554/129759340-5f9d5304-8e5c-4bce-8b28-18837ec755e5.png">

building on the command line works fine, restarting the language server does not change anything.

Any help would be greatly appreciated (about to start teaching :-/)

thanks!

**Comment by ulugbekna** [comment]
@etanter I updated the README [here](https://github.com/ulugbekna/vscode-ocaml-platform/tree/update-readme). Could you read the "Getting Started" and "FAQ" sections and see if the issue persists? Your setup seems basic enough for the extension to work excellent; I also can't reproduce the issue with the exact same setup. If the issue persists, I'll be happy to jump on a call or something.

I think the problem that @junknet has is a much more involved one and concerns `go-to-definition` rather than `unbound module`.

**Comment by etanter** [comment]
@ulugbekna thanks for updating the README file. As it turns out, in VS Code I was opening a _folder_, not a _workspace_, and that seems to have been the source of the problem. By starting with a workspace, everything works as expected. 
(On the way I learnt about the use of fswatch for instant rebuild, that's very helpful.)

Thanks a lot!

**Comment by junknet** [comment]
Maybe I have to compile first.
