### ISSUE TITLE
Sandbox not picked up on a project with esy on linux.

### ISSUE THREAD

**Issue by cician** [ocamllabs/vscode-ocaml-platform#758]
Hi. I tried using vscode-ocaml-platform extension in vscode to hack on [grain lang](https://grain-lang.org), but have trouble making it work. I'm not very familiar with the ocaml/reason ecosystem, so please bear with me. 

The grain project uses reason (not rescript) with esy and should be setup in a way to use a local ocaml sandbox. I was told it shouldn't be necessary to separately install esy, opam or anything like that and that everything get pulled by yarn. Compilation of the project from the command line works correctly, so esy and reason seems to work fine, but the extension doesn't seem to pick up the sandbox from the project and by extension the ocaml language server doesn't start because its not found in the global sandbox or on system path.

In vscode get these messages when opening the project:
- Error starting server: Sandbox initialisation failed: ocaml-lsp-server is not installed
- OCaml Platform is using the package manager and sandbox available in the environment. Pick a particular package manager and sandbox by clicking the button below
- This workspace is configured to use an esy sandbox, but esy isn't available

Here's what it looks like:
![image](https://user-images.githubusercontent.com/2879867/139684159-101b0b23-2277-43d8-b248-21a88551c40b.png)
![image](https://user-images.githubusercontent.com/2879867/139686335-4961d2f1-f2d6-401b-a038-dcebc0c3566e.png)

I'll provide any additional and ask fine folks from the grain's core team about the project setup if necessary.
Thank you.

# Operation system information
Ubuntu Linux 20.04 LTS.

# VS Code version
1.61.2

# OCaml Platform Extension version
1.8.4

# OCaml-LSP version
1.4.1

# Reproducible setup (some codebase, for example, where we can see the bug happening) the problem
The codebase is https://github.com/grain-lang/grain.

I've reproduced the setup in a Virtualbox VM with clean Ubuntu 20.04 LTS installation. (Have to install it, live CD doesn't have enough space in RAM disk).

Install git and curl.
`sudo apt install git curl`

This bash script installs node, vscode, clones the grain repo and opens vscode with the ocaml extension installed:
```bash
#!/bin/bash

set -e

mkdir ~/testgrain

cd ~/testgrain

wget https://nodejs.org/download/release/v14.18.1/node-v14.18.1-linux-x64.tar.xz

wget https://az764295.vo.msecnd.net/stable/6cba118ac49a1b88332f312a8f67186f7f3c1643/code-stable-x64-1634657157.tar.gz

tar -xf node-v14.18.1-linux-x64.tar.xz

tar -xf code-stable-x64-1634657157.tar.gz

echo "export PATH=~/testgrain/node-v14.18.1-linux-x64/bin:\$PATH" >> ~/.profile

echo "export PATH=~/testgrain/VSCode-linux-x64/bin:\$PATH" >> ~/.profile

. ~/.profile

source ~/.profile

npm install -g yarn

git clone git://github.com/grain-lang/grain

cd grain

yarn

yarn compiler build

yarn vscode

code --install-extension ocamllabs.ocaml-platform

code .
```

Note that I'm installing v14 here because that's officially supported by grain-lang, but tried v16 and the result is the same.

# Output View information described above
The commands `OCaml: Show OCaml Platform Extension Output` and `OCaml: Show OCaml Commands Output` don't show up in the command palette. Other commands do however, like `OCaml: Select a Sandbox for this Workspace`.

Going manually to "OCaml Commands" i see
```
$ which ocamllsp

```

and under "OCaml Platform Extension" i see
```
external command {
  "bin": "which",
  "args": [
    "ocamllsp"
  ]
}

external command (finished) {
  "bin": "which",
  "args": [
    "ocamllsp"
  ],
  "result": {
    "exitCode": 1,
    "stdout": "",
    "stderr": ""
  }
}

external command {
  "bin": "/bin/sh",
  "args": [
    "-c",
    "bash"
  ]
}
```
Which of course means that it doesn't find ocamllsp.
Running `esy which ocamllsp` from a yarn script does find it under `/home/tetsu/.esy/3___________________________________________________________________/i/opam__s__ocaml_lsp_server-opam__c__1.4.1-a9c283ce/bin/ocamllsp`.

**Comment by ulugbekna** [comment]
I'm not very familiar with esy+reason setup, but I couldn't ignore such a detailed issue, so here you go:

I reproduced the problem with the dockerfile in the grain repo. The problem is that `esy` installed in the project-local yarn sandbox, so it's not in your PATH -- when you run `esy` it isn't found, but when you do `yarn exec -- esy` it is. (note: in order to find esy, we just parse your PATH variable and search for `esy`)

Several hacks that could fix things: 

1) put `esy` in your path and then launch vscode
2) install `esy` globally -- may result in a future esy version mismatch with upstream perhaps (?) 
3) maybe you could run vscode from the yarn sandbox `yarn exec -- code .` -- I'm not sure this will work

Let me know how it works out. 

i) Also, there is a dockerfile, which could potentially make things easier to setup.
ii) There is also `yarn vscode` command by the grain team (see `package.json` in the project root) that sets up the vscode toolchain to hack on grain, and then you can install `OCaml Platform` extension from the marketplace and things should work fine. 

It works for me with the correct sandbox picked up (though the list of sandboxes shown is incorrect somehow):

![image](https://user-images.githubusercontent.com/16353531/139696378-49185dff-199a-4645-a52d-6056880953ae.png)


---

> The commands OCaml: Show OCaml Platform Extension Output and OCaml: Show OCaml Commands Output don't show up in the command palette.

These commands will be available in the new release; hopefully, somewhat soon.

**Comment by cician** [comment]
It works if I do any of the first three suggested points. Thank you! I haven't tried anything related to docker.

I can see the different sandbox in the status bar now instead of "Global OCaml" and various language features like code suggestions seem to work now. 

Adding esy from grain's node_modules to PATH does work.

Running `yarn exec -- code .` also works (before adding esy from node_modules to PATH).

Installing esy globally does work in the VM (again, without altered PATH from he first point). It does not work however on my main OS installation. Here installing esy both through npm or yarn doesn't change anything. The extension continues to report "This workspace is configured to use an esy sandbox, but esy isn't available".

A grain-lang dev is also looking into how to change the project settings. So if I understand correctly, one aspect of it is that grain was supposed to work without esy installed globally, but actually doesn't. The other aspect is that on my machine even if esy is installed glabally, the extension doesn't find it. This part is not reproducible with steps I provided above. I'll try to investigate differences between my OS and the VM, but at this point more out of curiosity than necessity.

**Comment by ulugbekna** [comment]
obtaining the result of `yarn exec -- which esy`, putting it in your path, and launching vscode with the PATH should do the job;

there is "Custom" sandbox in the extension, where you can specify how to run your programs, eg put `yarn exec -- esy -P <path> $prog $args`, where `<path>` is the path to your esy sandbox, usually where your `package.json` or `esy.json` (if I remember the name right) is located. I'm not sure it works properly, however -- testing it out to fix the problem was unsuccessful for me

**Comment by cician** [comment]
A grain-lang developer found a solution equivalent to what you suggested above, if I understand correctly what's happening (https://github.com/grain-lang/grain/pull/1016). With this esy doesn't need to be installed globally and the issue specific to my setup is circumvented.

As for globally installed esy not being found on my setup, I haven't been able to reproduce the issue in the VM, so I'm closing this issue. If you want me to dig deeper into the cause, let me know.

Thank you for your time.

**Comment by ulugbekna** [comment]
Glad I was helpful @cician
Good luck!
