### ISSUE TITLE
Specifying a path to binaries

### ISSUE THREAD

**Issue by phated** [ocamllabs/vscode-ocaml-platform#760]
In #758, it was noted that esy couldn't be found in the user's PATH and a solution was provided to hoist a local esy installation into the users PATH.

However, when digging deeper into this, I found that vscode doesn't always start vscode in the proper directory—notably on Windows (ref https://github.com/microsoft/vscode/issues/43237).

The ideal solution to this problem would be to allow overriding the location of the various binaries that this extension searches for. Does it make sense to allow the binaries to accept a specific filepath, otherwise fallback to looking on the PATH?

**Comment by rgrinberg** [comment]
What about setting up a "custom" sandbox? There you can override PATH to resolve to whatever binaries you want.

**Comment by phated** [comment]
That's our current solution, but you have to have an external script that calculates an absolute path since vscode will be running outside the project directory.

**Comment by tmattio** [comment]
> The ideal solution to this problem would be to allow overriding the location of the various binaries that this extension searches for. Does it make sense to allow the binaries to accept a specific filepath, otherwise fallback to looking on the PATH?

I think that's a common pattern for VSCode extensions (a typical example is the Python extensions, which will use the virtualenvs packages but also allows you to specify a custom path), so I'm in favor.

**Comment by ulugbekna** [comment]
@phated , can't the problem be fixed by installing `esy` globally, as the maintainers instruct in esy "Getting started" page, or having esy in PATH when launching vscode? The extension then should automatically detect an esy sandbox and provide a smooth workflow. 

---

Re: settings to specify binary path

That could happen at some point in future, but 
1) aren't there easier ways to fix this particular problem? Making esy global or making sure esy is in the PATH when launching vscode
2) we provide some flexibility already: one can use either `Custom` sandbox or use `Global` and set all binary paths in their PATH before launching vscode
3) adding settings to specify binary paths will add complexity and technical debt to the code:
    For example, currently ocaml-lsp looks up binaries (ocamlformat, dune, etc) in PATH. If we add a setting to specify a path to ocaml-lsp, they need to make sure that either the binary is available in path or they specify their paths in the rest of settings, which is error-prone and adds complexity and debt.

**Comment by rgrinberg** [comment]
> That's our current solution, but you have to have an external script that calculates an absolute path since vscode will be running outside the project directory.

While that is a little clunky, your situation isn't all that common so I deem this workaround sufficient.

I'd prefer not to create an additional layer of knobs for customizing binary locations. Especially if this layer is going to be only usable for exactly 3 binaries inside one extension. Therefore, I will reject this feature request. Sorry about that.
