### ISSUE TITLE
ocaml.open-repl doesn't work if the repl has been closed previously

### ISSUE THREAD

**Issue by Khady** [ocamllabs/vscode-ocaml-platform#935]
I have an issue with `OCaml: Open REPL` or `OCaml: Evaluate Selection` when I have previously closed the repl created by one of those commands.

- run `OCaml: Open REPL`, a wild toplevel appears
- close the utop/repl that was just created with something like ^D
- run `OCaml: Open REPL` again, nothing happens, nothing is printed inside the `OCaml Platform Extension` output

When using vscode with remote-ssh this is especially annoying as `OCaml: Restart Language Server` or `Developer: Reload Window` are not enough to fix the situation, I have to do `Remote-SSH: Kill Current VS Code Server` and reconnect

With version v1.10.1

**Comment by aqjune** [comment]
I am experiencing this bug as well.

**Comment by aqjune** [comment]
It seems that this function is not being called at all even if a terminal is closed:

https://github.com/ocamllabs/vscode-ocaml-platform/blob/d3fc5410444e88f7835cb24262be760fe1daac15/src/repl.ml#L198-L199

**Comment by aqjune** [comment]
Diving further, the reason is that even if a user exits the REPL using Ctrl+D it actually does not dispose the Terminal object.

I tried to detour this problem by registering a function to `Vscode.Window.onDidChangeActiveTerminal` so that if the user closes REPL the Terminal object is disposed too.
However, this could not be done because I could not detect when the REPL is terminated. I tried using `Terminal.exitStatus` but no avail. It is returning None even if the REPL process is terminated.

Actually, looking at the implementation of VSCode, `exitStatus` is set to `Some exitcode` when `Terminal.dispose` is called. `$acceptTerminalClosed` at  https://github.com/microsoft/vscode/blob/7c5742f4b958f3c5efb2284ebaf1152d4d1abf27/src/vs/workbench/api/common/extHostTerminalService.ts#L567-L574 is called when it is disposed (https://github.com/microsoft/vscode/blob/7c5742f4b958f3c5efb2284ebaf1152d4d1abf27/src/vs/workbench/api/browser/mainThreadTerminalService.ts#L340-L342).
